services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19565:19565"
    environment:
      EULA: "TRUE"
      TYPE: FORGE
      VERSION: 1.20.1
      DIFFICULTY: "normal"
      MAX_PLAYERS: 15
      INIT_MEMORY: 2G 
      MAX_MEMORY: 4G
      SPAWN_PROTECTION: 0
      VIEW_DISTANCE: 12
      MOTD: \u00A76\u00A7lCapivara \u00A72\u00A7lSMP                            \u00A7ev\u00A7l1.3.1
      TZ: "America/Sao_Paulo"
      ENABLE_COMMAND_BLOCK: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    restart: unless-stoped
    volumes:
      - ./data:/data
    networks:
      minecraft:
        aliases:
          - minecraft

  prometheus:
    image: bitnami/prometheus
    tty: true
    stdin_open: true
    ports:
      - "9090:9090"
    restart: on-failure:3
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      minecraft:
        aliases:
          - prometheus

  grafana:
    image: grafana/grafana
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    restart: on-failure:3
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      minecraft:
        aliases:
          - grafana

  promtail:
    image: grafana/promtail
    tty: true
    stdin_open: true
    restart: on-failure:3
    volumes:
      - ./data/logs:/var/log
    networks:
      minecraft:
        aliases:
          - promtail
  
  loki:
    image: grafana/loki
    tty: true
    stdin_open: true
    ports:
      - "3100:3100"
    restart: on-failure:3
    networks:
      minecraft:
        aliases:
          - loki

networks:
  minecraft:
    name: minecraft
