global:
  scrape_interval: 30s 


scrape_configs:
- job_name: 'minecraft'
  static_configs:
    # Alvo determinado pela network e Prometheus Exporter
    - targets: ['minecraft:19565']
      labels:
        server_name: 'minecraft-docker'